### ISSUE TITLE
No money is debited when purchasing a unit!

### ISSUE THREAD

**Issue by Valera8994** [NikolaiF90/F90SimpleShopSystem#3]
No money is debited when purchasing a unit!  Money is debited for all items, but the balance in the soldier's store remains the same.

**Comment by NikolaiF90** [comment]
Bugs fixed with new [Overhaul Update v2.0.0](https://github.com/NikolaiF90/F90SimpleShopSystem/releases/tag/v2.0.0).

See [Changelog](https://github.com/NikolaiF90/F90SimpleShopSystem/blob/main/CHANGELOG.md) to see what's being updated.

Thanks for letting me know about the issue though
